### ISSUE TITLE
How to use the code?

### ISSUE THREAD

**Issue by Haider-BA** [mesnardo/pyIBM#1]
I am running on Ubuntu and getting the error:

`python pyIBM.py `

`           ----- pyIBM - START -----

           Traceback (most recent call last):
            File "pyIBM.py", line 39, in <module>
            main()
            File "pyIBM.py", line 25, in main
            Case(args.path)
           File "/home/user/Downloads/pyIBM-master/src/case.py", line 18, in __init__
           Case.path = os.getcwd() + '/' + path
           TypeError: cannot concatenate 'str' and 'NoneType' objects `

**Comment by mesnardo** [comment]
I am using `argparse` to parse the command-line.

I forgot to set a default value for the path of the simulation. 
This is why, when not providing the command-line argument `--path <directory>` or `-p <directory>`, the run stops because `path` is not defined.

**Comment by Haider-BA** [comment]
Thank you. It works.
